server:
  port: 8080
spring:
  application:
    name: "JavaSpringBoot3"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapter:
  restconsumer:
    timeout: 5000
    url: "https://run.mocky.io"
commons:
  jms:
    input-concurrency: 10
    input-queue: "DEV.QUEUE.1"
    input-queue-alias: ""
    output-concurrency: 10
    output-queue: "DEV.QUEUE.2"
    producer-ttl: 0
    reactive: true
ibm:
  mq:
    channel: "DEV.APP.SVRCONN"
    user: "app"
